# -*- coding: utf-8 -*-
"""Preprocesamiento_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ewx0-s22UA5QMywuOVk7xXbC-XmWFGJ
"""

import os
import numpy as np

"""### 1.0 Quitar Archivos .wav"""

path = "../Respiratory_Sound_Database/Respiratory_Sound_Database/audio_and_txt_files"

carpeta_enfermedades = os.listdir("../Respiratory_Sound_Database/Respiratory_Sound_Database/audio_and_txt_files/")

directorio = os.listdir(path)

len(directorio)

for file in directorio:
    if ".wav" in file:
        src = os.path.join(path,file)
        os.remove(src)
    else:
        continue

"""### 2.0 Mover Archivos a carpetas"""

path_carpetas_str ="../Respiratory_Sound_Database/Respiratory_Sound_Database/Enfermedades"

path_carpetas = os.listdir("../Respiratory_Sound_Database/Respiratory_Sound_Database/Enfermedades")

path_carpetas

for i in directorio:
    nombre_archivo = i.split("_")[0]
    for x in path_carpetas:
        if nombre_archivo == x:
            src = path + "/" + i
            dst = path_carpetas_str + "/" + x + "/" + i
            os.rename(src,dst)
            #Mover archivo a x

